%% 普通接口
-define(CMD_UPDATE_CHECK, 1111).
-define(CMD_USER_GUEST_LOGIN, 1122).

-define(CMD_USER_LOGIN, 1211).
-define(CMD_USER_REGISTER, 1222).
-define(CMD_USER_EDIT_PROFILE, 1233).

-define(CMD_USER_ENTER_ROOM, 1133).
-define(CMD_USER_SIT_ON_DESK, 1144).
-define(CMD_USER_LEAVE_DESK, 1155).
-define(CMD_USER_CHANGE_DESK, 1166).
-define(CMD_USER_PROMPT_READY, 1177).
-define(CMD_USER_READY_TO_PLAY, 1188).

-define(CMD_DESK_FA_PAI, 2211).
-define(CMD_DESK_PROMPT_USER_JIAO_DI_ZHU, 2222).
-define(CMD_DESK_JIAO_DI_ZHU, 2233).
-define(CMD_DESK_JIAO_DI_ZHU_FINISH, 2244).
-define(CMD_DESK_FA_DI_PAI, 2255).
-define(CMD_DESK_CHU_PAI, 2266).
-define(CMD_DESK_CARDS_VALIDATE, 2277).
-define(CMD_DESK_CRADS_PROMPT, 2288).
-define(CMD_DESK_DA_PAI_END, 2299).

%% 自动xxx接口
-define(CMD_AUTO_DESK_JIAO_DI_ZHU, 3311).
-define(CMD_AUTO_DESK_CHU_PAI, 3322).


%% 断线重连接口
-define(CMD_USER_CHECK_RESUME_PLAY, 4411).
-define(CMD_USER_RESUME_PLAY, 4422).

-define(CMD_QUERY_DESK_USERS, 5511).
-define(CMD_QUERY_DESK_FA_PAI, 5522).
-define(CMD_QUERY_DESK_PROMPT_USER_JIAO_DI_ZHU, 5533).
-define(CMD_QUERY_DESK_JIAO_DI_ZHU, 5544).
-define(CMD_QUERY_DESK_JIAO_DI_ZHU_FINISH, 5555).
-define(CMD_QUERY_DESK_FA_DI_PAI, 5566).
-define(CMD_QUERY_DESK_CHU_PAI, 5577).

%% 服务器接口
-define(CMD_CLIENT_CONNECTED, 9911).
-define(CMD_CLIENT_DISCONNECTED, 9922).
-define(CMD_OTHER_CLIENT_DISCONNECTED, 9933).